version = 1

test_patterns = [
  "**/*_test.rs",
  "**/test/**",
  "**/tests/**"
]

[[analyzers]]
name = "rust"
enabled = true

  [analyzers.meta]
  msrv = "stable"
  cyclomatic_complexity_threshold = "low"
